spring.application.name=notification-service
server.port=8020
spring.security.user.name=sneha
spring.security.user.password=sneha

# spring.datasource.url=jdbc:mysql://localhost:3306/notificationservice
# spring.datasource.username=notificationserviceuser
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.show-sql: true
# spring.jpa.hibernate.ddl-auto=update

logging.level.org.springdoc=DEBUG

# Eureka config
eureka.client.service-url.defaultZone=http://localhost:8010/eureka
eureka.instance.prefer-ip-address=true

# Swagger API: http://localhost:8020/swagger-ui.html

# Twilio
twilio.account.sid=ACf67f36cced99621e12614c12c8550dc6
twilio.auth.token=472180d1de2e9f6491d5324c78f3bc6e
twilio.phone.number=+919938235386
