spring.application.name=notification-service
server.port=8020
spring.security.user.name=sneha
spring.security.user.password=sneha
logging.level.org.springdoc=DEBUG

# Eureka config
eureka.client.service-url.defaultZone=http://localhost:8010/eureka
eureka.instance.prefer-ip-address=true

# Swagger API: http://localhost:8020/swagger-ui.html

# Twilio
twilio.account.sid=ACCOUNT_SID
twilio.auth.token=ACCOUNT_TOKEN
twilio.phone.number=PHONE_NUMBER
