spring.application.name=calender-service
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/calenderservice
spring.datasource.username=calenderserviceuser
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springdoc=DEBUG
eureka.client.service-url.defaultZone=http://localhost:8010/eureka


# Swagger API: http://localhost:8080/swagger-ui.html

